esphome:
  name: hexaone-k1-keypad
  friendly_name: K1 Keypad
  name_add_mac_suffix: true

substitutions:
  #####
  # LOGGER
  # Modes available: NONE, ERROR, WARN, INFO, DEBUG, VERBOSE, VERY_VERBOSE
  logger_level: "NONE"
  #####


packages:
  remote_package:
    url: https://github.com/TimothySteinert/testing
    ref: dev2
    refresh: 0s
    files:
      # Core features & diagnostics
    - packages/core/core-esp32.yaml
      #Logger
    - packages/core/logger.yaml
      # Web UI
    - packages/core/web-ui.yaml
      # Wifi
    - packages/connectivity/wifi.yaml

api:
