esphome:
  name: hexaone-k1-keypad
  friendly_name: K1 Keypad
  name_add_mac_suffix: true

substitutions:

  mmwave_internal: true
  automatic_backlight: "true"
  backlight_timeout: "60"


packages:
  remote_package:
    url: https://github.com/TimothySteinert/testing
    ref: dev2
    refresh: 0s
    files:
      #####
      # CORE SETTINGS
      # This package is required and sets up core features.
      - path: packages/core/core-esp32.yaml
      #####

      #####
      # REQUIRED PACKAGES
      # These packages are required. They do not contain any user configurable settings.
      - path: packages/tamper.yaml
      #####

      #####
      # OPTIONAL PACKAGES
      # These packages are optional. They can be commented in/out to add/remove functionality. They do not contain any user configurable settings.
      - path: packages/core/web-ui.yaml
      #####

      #####
      # CONNECTIVITY SETTINGS
      # 
      # - path: packages/connectivity/dhcp_ethernet.yaml
      # - path: packages/connectivity/static_ethernet.yaml
      - path: packages/connectivity/wifi.yaml
        vars:
          static_ip: "192.168.1.100"
          gateway: "192.168.1.1"
          subnet: "255.255.255.0"
          dns1: "192.192.1.1"
          dns2: "8.8.8.8"
      #####

      #####
      # LOGGER SETTINGS
      # Modes available: NONE, ERROR, WARN, INFO, DEBUG, VERBOSE, VERY_VERBOSE
      - path: packages/core/logger.yaml
        vars:
          logger_level: NONE
      #####

      #####
      # MMWAVE SETTINGS
      # Modes available: NONE, ERROR, WARN, INFO, DEBUG, VERBOSE, VERY_VERBOSE
      - path: packages/core/logger.yaml
        vars:
          logger_level: NONE
      #####

      #####
      # BACKLIGHT SETTINGS
      # Modes available: NONE, ERROR, WARN, INFO, DEBUG, VERBOSE, VERY_VERBOSE
      - path: packages/core/logger.yaml
        vars:
          logger_level: NONE
      #####



      # Tamper Switch
    - packages/mmwave.yaml
    - packages/backlight.yaml

api:
