esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true

substitutions:
  name: hexaone-k1-keypad
  friendly_name: K1 Keypad
  #####
  # LOGGER
  # Modes available: NONE, ERROR, WARN, INFO, DEBUG, VERBOSE, VERY_VERBOSE
  logger_level: "NONE"
  #####

  mmwave_internal: true
  automatic_backlight: "true"
  backlight_timeout: "60"


packages:
  remote_package:
    url: https://github.com/TimothySteinert/testing
    ref: dev2
    refresh: 0s
    files:
      # Core features & diagnostics
    - packages/core/core-esp32.yaml
      #Logger
    - packages/core/logger.yaml
      # Web UI
    - packages/core/web-ui.yaml
      # Wifi
    - packages/connectivity/wifi.yaml
      # Tamper Switch
    - packages/tamper.yaml
    - packages/mmwave.yaml
    - packages/backlight.yaml

api:
