esphome:
  name: hexaone-k1-keypad
  friendly_name: K1 Keypad

packages:
  remote_package:
    url: https://github.com/TimothySteinert/testing
    ref: dev2
    refresh: 0s
    files:
      # Core features & diagnostics
    - packages/core/core-esp32.yaml
      # Wifi
    - packages/connectivity/wifi.yaml

api:

logger:

web_server:
  port: 80

dashboard_import:
  package_import_url: github://TimothySteinert/testing/example/test2.yaml@dev2
  import_full_config: true
