esphome:
  name: hexaone-k1-keypad
  friendly_name: K1 Keypad
  name_add_mac_suffix: true

packages:
  remote_package:
    url: https://github.com/TimothySteinert/testing
    ref: dev2
    refresh: 0s
    files:
      # Core features & diagnostics
    - packages/core/core-esp32.yaml
      # Wifi
    - packages/connectivity/wifi.yaml

api:

logger:

web_server:
  port: 80
