# Copyright (c) 2025 HexaOne – Licensed under the MIT License – See LICENSE.md
esphome:
  name: hexaone-k1-keypad
  friendly_name: K1 Keypad
  name_add_mac_suffix: true


#####
# GLOBAL SETTINGS
#
# This configuration is modular and built from packages.
# - Each package only consumes the vars it needs; unused vars are ignored.
# - To enable/disable features, comment or uncomment package paths.
# - To adjust behaviour, edit the vars under each package include.
#
# Example:
# Connectivity → static_ip vars only apply to static_ethernet.yaml; ignored with DHCP.
# mmWave       → mmwave_hidden_ha controls whether the sensor is exposed to HA.
# Logger       → logger_level sets log verbosity.
#####

packages:
  remote_package:
    url: https://!secret github_token@github.com/Hexa-One/K1-Keypad.git
    ref: main
    refresh: 0s
    files:
      #####
      # REQUIRED PACKAGES
      # These packages are required. They do not contain any user configurable settings.
      - path: packages/core/esp32.yaml
      - path: packages/lights/backlight.yaml
      - path: packages/input/tamper.yaml
      #####

      #####
      # OPTIONAL PACKAGES
      # These packages are optional. They can be commented in/out to add/remove functionality.
      # They do not contain any user configurable settings.
      - path: packages/core/web-ui.yaml
      #####

      #####
      # CONNECTIVITY SETTINGS
      # Vars for static IP will only be utilised for static_ethernet.yaml. They are ignored when using DHCP.
      # Only one connectivity package should be active at a time.
      # Uncomment the required package path for your network mode:
      # - path: packages/connectivity/dhcp_ethernet.yaml
      # - path: packages/connectivity/static_ethernet.yaml
      - path: packages/connectivity/wifi.yaml
        vars:
          static_ip: "192.168.1.100"
          gateway: "192.168.1.1"
          subnet: "255.255.255.0"
          dns1: "192.192.1.1"
          dns2: "8.8.8.8"
      #####

      #####
      # API SETTINGS
      # Vars for API encryption key will only be utilised for encrypted-api.yaml. They are ignored when using unencrypted.
      # Only one API package should be active at a time.
      # Uncomment the required package path for your API mode:
      - path: packages/core/unencrypted-api.yaml
      # - path: packages/core/encrypted-api.yaml
        vars:
          api_key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx="
      #####

      #####
      # LOGGER SETTINGS
      # Modes available: NONE, ERROR, WARN, INFO, DEBUG, VERBOSE, VERY_VERBOSE
      - path: packages/core/logger.yaml
        vars:
          logger_level: NONE
      #####

      # MMWAVE SETTINGS
      # Modes available: "true": mmwave is hidden from HA. "false": mmwave is exposed to HA.
      - path: packages/input/mmwave.yaml
        vars:
          mmwave_hidden_ha: "true"
      #####

dashboard_import:
  package_import_url: github://TimothySteinert/testing/example/test2.yaml@dev2
  import_full_config: true
