substitutions:
  name: hexaone-k1-keypad
  friendly_name: K1 Keypad
  project_name: hexaone.k1keypad
  project_version: "0.1"

packages:
  remote_package:
    url: https://github.com/TimothySteinert/testing
    ref: dev2
    refresh: 0s
    files:
      # Core features & diagnostics
      - packages/core/core-esp32.yaml

# Core already includes logger, api, ota, sensors, text_sensors

api:

logger:

# Connectivity / provisioning (bootstrap only, no secrets)
wifi:
  ap:

captive_portal:

esp32_improv:
  authorizer: none

improv_serial:

dashboard_import:
  package_import_url: github://TimothySteinert/testing/example/test2.yaml@dev2
  import_full_config: true
