substitutions:
  static_ip: "192.168.1.100"
  gateway: "192.168.1.1"
  subnet: "255.255.255.0"
  dns1: "192.192.1.1"
  dns2: "8.8.8.8"

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk:
    pin:
      number: GPIO0
      ignore_strapping_warning: true
    mode: CLK_EXT_IN
  phy_addr: 0
  power_pin: GPIO16

  manual_ip:
    static_ip: ${static_ip}
    gateway: ${gateway}
    subnet: ${subnet}
    dns1: ${dns1}
    dns2: ${dns2}

text_sensor:
  - platform: ethernet_info
    ip_address:
      name: Ethernet IP Address
      entity_category: diagnostic
