substitutions:
  name: hexaone-k1-keypad
  friendly_name: K1 Keypad
  project_name: hexaone.k1keypad
  project_version: "0.1"
  
  ####
  # CONFIGURABLE OPTIONS
  
  # Exposes the MMWAVE sensor to HA for automations
  mmwave_internal: "true"   # Set to "false" if you want it exposed to HA
  api_key: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=" #API encryption key. Change from Default
  wifi_ssid: "xxx"
  wifi_password: "xxx"

  ####
  # STATIC IP SETTINGS
  # These values are only used if you select one of the static connectivity packages
  # (static_wifi.yaml or static_ethernet.yaml).
  # If you are using DHCP (dhcp_wifi.yaml or dhcp_ethernet.yaml), these can be ignored.
  static_ip: "192.168.1.150"
  gateway: "192.168.1.254"
  subnet: "255.255.255.0"
  dns1: "192.192.1.254"
  dns2: "1.1.1.1"

  #BACKLIGHT CONTROL
  # Backlight timeout in seconds (0–600)
  backlight_timeout: "60"
  automatic_backlight: "true"   # "true" = default AUTO, "false" = default MANUAL

#### 
# PACKAGES
# Each package includes keypad features.
# Remove or comment out any packages that you do not need or want.
# If you're developing/installing locally, replace the github package line with the local package include above it.
packages:
  remote_package:
    url: https://github.com/TimothySteinert/testing
    ref: master
    refresh: 5min
    files:

      ####
      # CORE
      # This package is required and sets up core features.
      - packages/core-esp32.yaml

      ####
      # WEB UI
      # This package is optional and sets up the web ui.
      - packages/webui.yaml

      ####
      # CONNECTIVITY
      # Choose ONE connectivity method below by uncommenting the line:
      # Wi-Fi (DHCP or Static) OR Ethernet (DHCP or Static)
      # - packages/connectivity/dhcp_wifi.yaml  # Wi-Fi with DHCP
      - packages/connectivity/static_wifi.yaml  # Wi-Fi with Static IP
      # - packages/connectivity/dhcp_ethernet.yaml  # Ethernet with DHCP
      # - packages/connectivity/static_ethernet.yaml  # Ethernet with Static IP

      ####
      # INPUT
      - packages/tamper.yaml
      - packages/mmwave.yaml

      ####
      # HEXAONE STATE TRACKING
      # This package is required. It tracks the alarm state via HexaOne Keypad HACS integration.
      - packages/hexaone_state.yaml

      ####
      # UART
      - packages/uart_tx.yaml
      - packages/uart_rx.yaml
      - packages/input_handling.yaml
      - packages/alarm_ctrl.yaml



      ####
      # BACKLIGHT
      - packages/backlight.yaml
