substitutions:
  encryption_enabled: "false"
  api_key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX="

api:
  # Always present
  <<: !include
    - if:
        condition: "return ${encryption_enabled} == \"true\";"
        then:
          - encryption:
              key: ${api_key}
