esphome:
  min_version: "2025.7.0" 
  on_boot:
    - priority: 800.0
      then:
        - text_sensor.template.publish:
            id: device_id
            state: !lambda return get_mac_address();
        - text_sensor.template.publish:
            id: project_version
            state: !lambda return ESPHOME_PROJECT_VERSION;

esp32:
  board: wt32-eth01
  framework:
    type: esp-idf
    version: recommended

text_sensor:
  - platform: template
    name: Device ID
    id: device_id
    entity_category: diagnostic
    update_interval: never

  - platform: version
    id: esphome_version
    name: ESPHome Version
    hide_timestamp: true

  - platform: template
    name: Project version
    id: project_version
    entity_category: diagnostic
    update_interval: never

sensor:
  - platform: uptime
    name: Uptime
    id: uptime_sensor
    entity_category: diagnostic

ota:
  - platform: esphome
    id: hexaone_ota

dashboard_import:
  package_import_url: github://TimothySteinert/testing/example/test2.yaml@dev2
  import_full_config: true
