globals:
  - id: flash_state
    type: bool
    restore_value: no
    initial_value: 'false'

interval:
  - interval: 500ms
    then:
      - lambda: |-
          id(flash_state) = !id(flash_state);

substitutions:
  led_id: led_default
  led_name: LED Default

light:
  - platform: rgb
    id: ${led_id}
    name: "${led_name}"
    red: ${led_id}_red
    green: ${led_id}_green
    blue: ${led_id}_blue
    restore_mode: ALWAYS_OFF
    effects:
      - lambda:
          name: Flash Sync
          update_interval: 200ms   # checks global state regularly
          lambda: |-
            if (initial_run) {
              id(${led_id}).turn_on()
                .set_rgb(1.0, 0.0, 0.0)
                .set_brightness(1.0f)
                .set_transition_length(0)
                .perform();
              return;
            }

            if (id(flash_state)) {
              id(${led_id}).turn_on()
                .set_rgb(1.0, 0.0, 0.0)
                .set_brightness(1.0f)
                .set_transition_length(50)
                .perform();
            } else {
              id(${led_id}).turn_on()
                .set_brightness(0.0f)
                .set_transition_length(50)
                .perform();
            }
