binary_sensor:
  - platform: gpio
    id: mmwave_sensor
    name: "${friendly_name} mmWave Sensor"
    device_class: motion
    internal: ${mmwave_internal}
    pin:
      number: GPIO34
      mode: INPUT
    on_press:
      - if:
          condition:
            switch.is_on: automatic_backlight_switch
          then:
            - light.turn_on: backlight_light

