binary_sensor:
  - platform: gpio
    id: mmwave_sensor
    name: "${friendly_name} mmWave Sensor"
    device_class: motion
    internal: !lambda return !${expose_mmwave};
    pin:
      number: GPIO39
      mode: INPUT
