binary_sensor:
  - platform: gpio
    id: mmwave_sensor
    name: "${friendly_name} mmWave Sensor"
    device_class: motion
    internal: ${mmwave_internal}
    pin:
      number: GPIO34
      mode: INPUT
    on_press:
      - if:
          condition:
            lambda: 'return id(g_automatic_backlight);'
          then:
            - logger.log: "mmWave triggered -> turning ON backlight"
            - light.turn_on: backlight_light
          else:
            - logger.log: "mmWave triggered but auto mode is disabled"
