binary_sensor:
  - platform: gpio
    id: tamper_switch
    name: "${friendly_name} Tamper Switch"
    device_class: tamper
    pin:
      number: GPIO35
      mode: INPUT
      inverted: true
    filters:
      - delayed_on_off: 50ms
